### ISSUE TITLE
Response body from job_titles, locations, and supervisors does not match with documentation

### ISSUE THREAD

**Issue by iande** [Compli/partners-api#1]
When calling the `job_titles`, `locations`, or `supervisors` functions, I am getting response bodies with a different structure than what's shown in the documentation. Here is an example of the responses I've been getting:

```js
{
  "payload" => {
    "client_unique_identifier" => "f8c6fc73c0d176c3eaefbf52e9ac525a",
    "result" => "success",
    "error_code" => nil,
    "error_desc" => nil,
    "warnings" => [],
    "data"=> [
      {
        "result" => "searched",
        "error_code" => nil,
        "error_desc" => nil,
        "data" => [ ... ]
      }
    ]
}
```

It seems that the top-level `data` key holds an array containing a single object that resembles a second payload, and the `data` key in this object is the array of job titles, supervisors, or locations.

**Comment by kcook001** [comment]
Updated, thanks!
